import React, { useState } from "react";
import EcomCard from "./EcomCard";

const EcomCardApi = () => {
  const [ecomData, setEcomData] = useState([
    {
      id: 1,
      name: "Wireless Mouse",
      category: "Electronics",
      brand: "Logitech",
      price: 899,
      rating: 4.5,
      stock: 35,
      image: "https://images.unsplash.com/photo-1527814050087-3793815479db?w=500",
    },
    {
      id: 2,
      name: "Gaming Keyboard",
      category: "Electronics",
      brand: "Redragon",
      price: 2499,
      rating: 4.7,
      stock: 20,
      image: "https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?w=500",
    },
    {
      id: 3,
      name: "Smart Watch",
      category: "Wearables",
      brand: "Noise",
      price: 3499,
      rating: 4.4,
      stock: 15,
      image:  "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=500",
    },
    {
      id: 4,
      name: "Bluetooth Speaker",
      category: "Electronics",
      brand: "JBL",
      price: 1999,
      rating: 4.6,
      stock: 12,
      image: "https://picsum.photos/300?random=4",
    },
    {
      id: 5,
      name: "Running Shoes",
      category: "Fashion",
      brand: "Nike",
      price: 4599,
      rating: 4.8,
      stock: 10,
      image: "https://picsum.photos/300?random=5",
    },
    {
      id: 6,
      name: "Backpack",
      category: "Accessories",
      brand: "Skybags",
      price: 1499,
      rating: 4.3,
      stock: 28,
      image: "https://picsum.photos/300?random=6",
    },
    {
      id: 7,
      name: "Office Chair",
      category: "Furniture",
      brand: "GreenSoul",
      price: 6999,
      rating: 4.5,
      stock: 8,
      image: "https://picsum.photos/300?random=7",
    },
    {
      id: 8,
      name: "Study Table",
      category: "Furniture",
      brand: "IKEA",
      price: 5499,
      rating: 4.4,
      stock: 5,
      image: "https://picsum.photos/300?random=8",
    },
    {
      id: 9,
      name: "Water Bottle",
      category: "Home",
      brand: "Milton",
      price: 499,
      rating: 4.2,
      stock: 50,
      image: "https://picsum.photos/300?random=9",
    },
    {
      id: 10,
      name: "LED Desk Lamp",
      category: "Home",
      brand: "Philips",
      price: 1199,
      rating: 4.6,
      stock: 18,
      image: "https://picsum.photos/300?random=10",
    },
    {
      id: 11,
      name: "Cricket Bat",
      category: "Sports",
      brand: "SS",
      price: 3299,
      rating: 4.5,
      stock: 9,
      image: "https://picsum.photos/300?random=11",
    },
    {
      id: 12,
      name: "Football",
      category: "Sports",
      brand: "Nivia",
      price: 899,
      rating: 4.3,
      stock: 22,
      image: "https://picsum.photos/300?random=12",
    },
    {
      id: 13,
      name: "Coffee Mug",
      category: "Kitchen",
      brand: "Cello",
      price: 299,
      rating: 4.1,
      stock: 60,
      image: "https://picsum.photos/300?random=13",
    },
    {
      id: 14,
      name: "Air Fryer",
      category: "Kitchen",
      brand: "Prestige",
      price: 5499,
      rating: 4.7,
      stock: 7,
      image: "https://picsum.photos/300?random=14",
    },
    {
      id: 15,
      name: "Laptop Stand",
      category: "Accessories",
      brand: "Portronics",
      price: 999,
      rating: 4.4,
      stock: 19,
      image: "https://picsum.photos/300?random=15",
    },
    {
      id: 16,
      name: "Power Bank",
      category: "Electronics",
      brand: "Mi",
      price: 1599,
      rating: 4.6,
      stock: 14,
      image: "https://picsum.photos/300?random=16",
    },
    {
      id: 17,
      name: "Sunglasses",
      category: "Fashion",
      brand: "Ray-Ban",
      price: 2999,
      rating: 4.8,
      stock: 11,
      image: "https://picsum.photos/300?random=17",
    },
    {
      id: 18,
      name: "Perfume",
      category: "Beauty",
      brand: "Bella Vita",
      price: 799,
      rating: 4.3,
      stock: 30,
      image: "https://picsum.photos/300?random=18",
    },
    {
      id: 19,
      name: "Yoga Mat",
      category: "Fitness",
      brand: "Boldfit",
      price: 699,
      rating: 4.5,
      stock: 24,
      image: "https://picsum.photos/300?random=19",
    },
    {
      id: 20,
      name: "Headphones",
      category: "Electronics",
      brand: "Boat",
      price: 1799,
      rating: 4.6,
      stock: 17,
      image: "https://picsum.photos/300?random=20",
    },
  ]);

  let deleteBtn = (id) => {
    let deleteitm = ecomData.filter((elem)=> elem.id !== id)
    setEcomData(deleteitm)
  }
  return (
    <div className="flex p-4 flex-wrap gap-2 items-center justify-center bg-amber-200">
      {ecomData.map((elem) => {
        return <EcomCard Edata={elem} del={deleteBtn}/>;
      })}
    </div>
  );
};

export default EcomCardApi;
